from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b991e1e0150b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wind_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('wind_speed_kph', sa.Float(), nullable=True),
        sa.Column('wind_speed_mph', sa.Float(), nullable=True),
        sa.Column('wind_direction', sa.String(length=50), nullable=True),
        sa.Column('wind_degree', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wind_data')
    # ### end Alembic commands ###