databaseType = "MySql"
id = "1db35dbb-a9a2-4f36-af59-c6d0b0894e14"
name = "flyway_weather_db_mysql"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
schemaModel = "schema-model"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.mysql]
url = "jdbc:mysql://localhost:3306/weather_db_mysql"
schemas = [ "weather_db_mysql" ]
