databaseType = "MySql"
id = "a001f116-7c65-4d4c-a00d-cbc5d6fa9a5f"
name = "flyway_mysql"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
schemaModel = "schema-model"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.target1]
url = "jdbc:mysql://localhost:3306"
schemas = [ "weather_db_mysql" ]
displayName = "migrate_to_mysql"
